name: main 
on:
  push:  # 为了调试方便，修改代码之后push上去即可以看到效
    paths: # 指定只有哪些文件修改了才会触发该工作流程
      - .github/workflows/main.yml
  schedule:
    - cron: "0 0 * * *"
jobs:
#将工作流程中运行的所有作业组合在一起
  build:
  #定义名为 build 的作业。 子键将定义作业的属性 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.1
      - name: install pip packages
        run: |
          python -m pip install --upgrade pip
          pip3 install requests
      - name: main
        run: |
          python3 main.py
